name: Gold Bot

on:
  workflow_dispatch:  # لتشغيله يدويًا
  schedule:
    - cron: "0 10-22 * * *"  # كل ساعة من 10 صباحًا حتى 10 مساءً

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install "python-telegram-bot[job-queue]==20.7" requests beautifulsoup4 plotly matplotlib

      - name: Run bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GOLDPRICEZ_KEY: ${{ secrets.GOLDAPI_KEY }}
        run: python gold_bot.py
